listener:
  - address: "localhost"
    port: 8009
    threads: 10
    path:
      - prefix: "/ajproxy"
        connections: 20
        threads: 10
        timeout: 5
        host:
          - address: "localhost"
            port: 8443
            ssl: "true"
